### ISSUE TITLE
Loop closure messing up 3D map reconstruction

### ISSUE THREAD

**Issue by 67K-You** [NeBula-Autonomy/LAMP#4]
Hello and thanks for making LAMP available through this open source implementation.

I'm trying to test LAMP's inter-robot loop closure in simulation with a setup of 3 turtlebots exploring willowgarage using LAMP's default parameters. The 3D lidar map is quite accurate at the beginning of the exploration. 
<img src="https://user-images.githubusercontent.com/62215972/176586172-505446dc-2084-45c9-b6b2-2945baa75bba.png" alt="drawing" width="395"/> <img src="https://user-images.githubusercontent.com/62215972/176586178-a8aa512f-6122-4996-a570-bd3551122c04.png" alt="drawing2" width="405"/>
<img src="https://user-images.githubusercontent.com/62215972/176586180-37f34e6f-6d4a-4be1-98b1-6b9c34fb271b.png" alt="drawing3" width="400"/> <img src="https://user-images.githubusercontent.com/62215972/176586183-338ddd93-4544-4d94-b2f0-a3fc5ba740c5.png" alt="drawing4" width="400"/>

However after the first loop closure the map is badly reconstructed: 
<img src="https://user-images.githubusercontent.com/62215972/176586184-04d4ec1a-b20d-4aaf-9ffd-704ccd62e40c.png" alt="drawing5" width="650"/>

Do you know what might cause this issue ?

I believe there might be issues with the parameters of the Levenberg–Marquardt optimizer. I joined the [output of the optimizer](https://github.com/NeBula-Autonomy/LAMP/files/9016667/output-LM-optimizer.txt) as well as [the parameters of the simulation
](https://github.com/NeBula-Autonomy/LAMP/files/9016678/parameters.txt).

Finally you can find an archive containing [the logs of the simulation](https://github.com/NeBula-Autonomy/LAMP/files/9016686/logs_setup.tar.gz).

Thanks for your help !

**Comment by yunzc** [comment]
Hi, 
Thanks for trying out LAMP! 
There's a few things that you can try:
1. Do the keyed scans make sense? Make sure that you are not down-sampling too much otherwise you would get bad loop closures. To tune the parameters related to this, take a look [here](https://github.com/NeBula-Autonomy/LAMP/blob/main/lamp/config/filter_parameters.yaml) or however you are filtering your point-cloud to create the keyed scans. 
2. Do the output from the loop closures make sense? Take a look at the output [topic](https://github.com/NeBula-Autonomy/LAMP/blob/main/loop_closure/launch/loop_closure_modules.launch#L79) of the loop closure module to make sure if the transforms are kind of what you expect. Otherwise you can tune the loop closure detection [parameters](https://github.com/NeBula-Autonomy/LAMP/blob/main/loop_closure/config/laser_parameters.yaml)
3. How is the outlier rejection (probably GNC) doing. There should be a terminal output like xx number of loop closures detected with xx inliers. If all the loop closures are accepted, there's probably something weird going on, and you can increase the strictness of GNC by tuning alpha in this [file](https://github.com/NeBula-Autonomy/LAMP/blob/main/lamp_pgo/config/pgo_parameters.yaml)
4. In general, make sure that the book-keeping is done correctly. I.e., each robot should have a unique prefix such as what is defined [here](https://github.com/NeBula-Autonomy/LAMP/blob/main/lamp/launch/turn_on_lamp.launch#L80)
